apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flask-api
spec:
  selector:
    matchLabels:
      app: flask
  replicas: 2
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: alizard0/ws:0.0.1
        ports:
        - containerPort: 5000